#!/usr/bin/python3
def canUnlockAll(boxes):
list = [0]
for i in boxes[0]:
list.append(i)
for j in list:
for key in boxes[j]:
***compare and extract the difference between 2 lists***
***append list with new differences***
***then check this differeences with the rest of the list***
